### ISSUE TITLE
Fedora 27 rebuild

### ISSUE THREAD

**Issue by orpiske** [aflyhorse/libjpeg-specs#1]
Hello, 

Thanks for maintaining this COPR package. Do you have any plans to rebuild this packages Fedora 27? I think this would be very useful for those of us who need this library.

**Comment by aflyhorse** [comment]
Thank you for your feedback. I've built the repo for fedora 27 and rawhide, and enabled the new feature "Follow Fedora branching".

**Comment by orpiske** [comment]
Thanks, that is very helpful. I [tested it](http://www.orpiske.net/2017/12/garmin-connect-iq-on-fedora/) and it seems to be working fine.

**Comment by aflyhorse** [comment]
You are more than welcome, I'm glad I was able to help.
